name: Build and push SSK's container image
run-name: ${{ gitea.actor }} is building and pushing SSK's container image
on: create

jobs:
  build-and-push-image:
    uses: homelab/workflows/.gitea/workflows/docker.yaml@7ec31032cf0ba6582542f9de5edfdbc8ad9b80ee
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
