name: Build and push SSK's container image
run-name: ${{ gitea.actor }} is building and pushing SSK's container image
on: create

jobs:
  build-and-push-image:
    uses: homelab/workflows/.gitea/workflows/docker.yaml@27396d3e6db37cd2c07d16253fe3bab015311b2e
    secrets: inherit
