name: Build and push SSK's container image
run-name: ${{ gitea.actor }} is building and pushing SSK's container image
on: create

jobs:
  build-and-push-image:
    uses: actions/workflows/.gitea/workflows/docker.yaml@7f885c347c8a0c89a7961d44ea148e86da180db1
    secrets: inherit
