// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using spotify_swiss_knife.DAL;

#nullable disable

namespace spotify_swiss_knife.Migrations
{
    [DbContext(typeof(SpotifyDbContext))]
    [Migration("20260507120507_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlbumArtist", b =>
                {
                    b.Property<string>("AlbumId")
                        .HasColumnType("text");

                    b.Property<string>("ArtistId")
                        .HasColumnType("text");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("AlbumArtists", (string)null);
                });

            modelBuilder.Entity("TrackArtist", b =>
                {
                    b.Property<string>("ArtistId")
                        .HasColumnType("text");

                    b.Property<string>("TrackId")
                        .HasColumnType("text");

                    b.HasKey("ArtistId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackArtists", (string)null);
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Album", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AlbumType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "album_type");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "popularity");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "release_date");

                    b.Property<string>("ReleaseDatePrecision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "release_date_precision");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "total_tracks");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Artist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Playlist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<DateTime?>("LastShuffled")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "snapshot_id");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.PlaylistTrackEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistTrackEntries");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Track", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AlbumId")
                        .HasColumnType("text");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "disc_number");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "duration_ms");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_local");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "track_number");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("AlbumArtist", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("spotify_swiss_knife.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackArtist", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("spotify_swiss_knife.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Album", b =>
                {
                    b.OwnsOne("spotify_swiss_knife.Models.ExternalUrls", "ExternalUrls", b1 =>
                        {
                            b1.Property<string>("AlbumId")
                                .HasColumnType("text");

                            b1.Property<string>("Spotify")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AlbumId");

                            b1.ToTable("Albums");

                            b1.HasAnnotation("Relational:JsonPropertyName", "external_urls");

                            b1.WithOwner()
                                .HasForeignKey("AlbumId");
                        });

                    b.OwnsMany("spotify_swiss_knife.Models.Image", "Images", b1 =>
                        {
                            b1.Property<string>("AlbumId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("Height")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "height");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "url");

                            b1.Property<int?>("Width")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "width");

                            b1.HasKey("AlbumId", "Id");

                            b1.ToTable("AlbumImages", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "images");

                            b1.WithOwner()
                                .HasForeignKey("AlbumId");
                        });

                    b.Navigation("ExternalUrls")
                        .IsRequired();

                    b.Navigation("Images");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Artist", b =>
                {
                    b.OwnsOne("spotify_swiss_knife.Models.ExternalUrls", "ExternalUrls", b1 =>
                        {
                            b1.Property<string>("ArtistId")
                                .HasColumnType("text");

                            b1.Property<string>("Spotify")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ArtistId");

                            b1.ToTable("Artists");

                            b1.WithOwner()
                                .HasForeignKey("ArtistId");
                        });

                    b.Navigation("ExternalUrls")
                        .IsRequired();
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Playlist", b =>
                {
                    b.OwnsOne("spotify_swiss_knife.Models.Owner", "Owner", b1 =>
                        {
                            b1.Property<string>("PlaylistId")
                                .HasColumnType("text");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("text")
                                .HasColumnName("Owner_DisplayName")
                                .HasAnnotation("Relational:JsonPropertyName", "display_name");

                            b1.HasKey("PlaylistId");

                            b1.ToTable("Playlists");

                            b1.HasAnnotation("Relational:JsonPropertyName", "owner");

                            b1.WithOwner()
                                .HasForeignKey("PlaylistId");

                            b1.OwnsOne("spotify_swiss_knife.Models.ExternalUrls", "ExternalUrls", b2 =>
                                {
                                    b2.Property<string>("OwnerPlaylistId")
                                        .HasColumnType("text");

                                    b2.Property<string>("Spotify")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Owner_ExternalUrls_Spotify");

                                    b2.HasKey("OwnerPlaylistId");

                                    b2.ToTable("Playlists");

                                    b2.HasAnnotation("Relational:JsonPropertyName", "external_urls");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerPlaylistId");
                                });

                            b1.Navigation("ExternalUrls")
                                .IsRequired();
                        });

                    b.OwnsOne("spotify_swiss_knife.Models.ExternalUrls", "ExternalUrls", b1 =>
                        {
                            b1.Property<string>("PlaylistId")
                                .HasColumnType("text");

                            b1.Property<string>("Spotify")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PlaylistId");

                            b1.ToTable("Playlists");

                            b1.HasAnnotation("Relational:JsonPropertyName", "external_urls");

                            b1.WithOwner()
                                .HasForeignKey("PlaylistId");
                        });

                    b.OwnsMany("spotify_swiss_knife.Models.Image", "Images", b1 =>
                        {
                            b1.Property<string>("PlaylistId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("Height")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "height");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "url");

                            b1.Property<int?>("Width")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "width");

                            b1.HasKey("PlaylistId", "Id");

                            b1.ToTable("PlaylistImages", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "images");

                            b1.WithOwner()
                                .HasForeignKey("PlaylistId");
                        });

                    b.Navigation("ExternalUrls")
                        .IsRequired();

                    b.Navigation("Images");

                    b.Navigation("Owner")
                        .IsRequired();
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.PlaylistTrackEntry", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.Playlist", "Playlist")
                        .WithMany("TrackEntries")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("spotify_swiss_knife.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Track", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.Album", "Album")
                        .WithMany("TrackList")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("spotify_swiss_knife.Models.ExternalUrls", "ExternalUrls", b1 =>
                        {
                            b1.Property<string>("TrackId")
                                .HasColumnType("text");

                            b1.Property<string>("Spotify")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TrackId");

                            b1.ToTable("Tracks");

                            b1.HasAnnotation("Relational:JsonPropertyName", "external_urls");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.OwnsMany("spotify_swiss_knife.Models.Image", "Images", b1 =>
                        {
                            b1.Property<string>("TrackId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("Height")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "height");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "url");

                            b1.Property<int?>("Width")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "width");

                            b1.HasKey("TrackId", "Id");

                            b1.ToTable("TrackImages", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "images");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("Album");

                    b.Navigation("ExternalUrls")
                        .IsRequired();

                    b.Navigation("Images");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Album", b =>
                {
                    b.Navigation("TrackList");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Playlist", b =>
                {
                    b.Navigation("TrackEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
