// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using spotify_swiss_knife.DAL;

#nullable disable

namespace spotify_swiss_knife.Migrations
{
    [DbContext(typeof(SpotifyDbContext))]
    [Migration("20260608173155_UpdateJmbagLength")]
    partial class UpdateJmbagLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlbumArtist", b =>
                {
                    b.Property<string>("AlbumId")
                        .HasColumnType("text");

                    b.Property<string>("ArtistId")
                        .HasColumnType("text");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("AlbumArtists", (string)null);

                    b.HasData(
                        new
                        {
                            AlbumId = "album-lunar-protocol",
                            ArtistId = "artist-luna-wave"
                        },
                        new
                        {
                            AlbumId = "album-feather-and-noise",
                            ArtistId = "artist-blackbird-theory"
                        },
                        new
                        {
                            AlbumId = "album-feather-and-noise",
                            ArtistId = "artist-ember-kite"
                        },
                        new
                        {
                            AlbumId = "album-cloud-garden-ep",
                            ArtistId = "artist-neon-meadow"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TrackArtist", b =>
                {
                    b.Property<string>("ArtistId")
                        .HasColumnType("text");

                    b.Property<string>("TrackId")
                        .HasColumnType("text");

                    b.HasKey("ArtistId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackArtists", (string)null);

                    b.HasData(
                        new
                        {
                            ArtistId = "artist-luna-wave",
                            TrackId = "track-midnight-circuit"
                        },
                        new
                        {
                            ArtistId = "artist-luna-wave",
                            TrackId = "track-gravity-bloom"
                        },
                        new
                        {
                            ArtistId = "artist-neon-meadow",
                            TrackId = "track-gravity-bloom"
                        },
                        new
                        {
                            ArtistId = "artist-blackbird-theory",
                            TrackId = "track-river-in-binary"
                        },
                        new
                        {
                            ArtistId = "artist-ember-kite",
                            TrackId = "track-static-sunrise"
                        },
                        new
                        {
                            ArtistId = "artist-neon-meadow",
                            TrackId = "track-solar-echo"
                        },
                        new
                        {
                            ArtistId = "artist-ember-kite",
                            TrackId = "track-solar-echo"
                        });
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Album", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AlbumType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "album_type");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "popularity");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "release_date");

                    b.Property<string>("ReleaseDatePrecision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "release_date_precision");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "total_tracks");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = "album-lunar-protocol",
                            AlbumType = "album",
                            Label = "Night Current Records",
                            Name = "Lunar Protocol",
                            Popularity = 74,
                            ReleaseDate = "2022-11-18",
                            ReleaseDatePrecision = "day",
                            TotalTracks = 2
                        },
                        new
                        {
                            Id = "album-feather-and-noise",
                            AlbumType = "album",
                            Label = "Vector Harbor",
                            Name = "Feather and Noise",
                            Popularity = 61,
                            ReleaseDate = "2021-06-10",
                            ReleaseDatePrecision = "day",
                            TotalTracks = 2
                        },
                        new
                        {
                            Id = "album-cloud-garden-ep",
                            AlbumType = "single",
                            Label = "Mirrorline",
                            Name = "Cloud Garden EP",
                            Popularity = 58,
                            ReleaseDate = "2024-02-02",
                            ReleaseDatePrecision = "day",
                            TotalTracks = 1
                        });
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("JMBAG")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Artist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = "artist-luna-wave",
                            Name = "Luna Wave"
                        },
                        new
                        {
                            Id = "artist-neon-meadow",
                            Name = "Neon Meadow"
                        },
                        new
                        {
                            Id = "artist-blackbird-theory",
                            Name = "Blackbird Theory"
                        },
                        new
                        {
                            Id = "artist-ember-kite",
                            Name = "Ember Kite"
                        });
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Playlist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<DateTime?>("LastShuffled")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "snapshot_id");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = "playlist-night-drive",
                            Description = "Synth-heavy tracks for late coding sessions",
                            Name = "Night Drive",
                            SnapshotId = "snapshot-001"
                        },
                        new
                        {
                            Id = "playlist-rainy-library",
                            Description = "Calmer cuts with longer runtimes",
                            Name = "Rainy Library",
                            SnapshotId = "snapshot-002"
                        });
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.PlaylistTrackEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistTrackEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlaylistId = "playlist-night-drive",
                            SortOrder = 0,
                            TrackId = "track-midnight-circuit"
                        },
                        new
                        {
                            Id = 2,
                            PlaylistId = "playlist-night-drive",
                            SortOrder = 1,
                            TrackId = "track-gravity-bloom"
                        },
                        new
                        {
                            Id = 3,
                            PlaylistId = "playlist-night-drive",
                            SortOrder = 2,
                            TrackId = "track-solar-echo"
                        },
                        new
                        {
                            Id = 4,
                            PlaylistId = "playlist-rainy-library",
                            SortOrder = 0,
                            TrackId = "track-river-in-binary"
                        },
                        new
                        {
                            Id = 5,
                            PlaylistId = "playlist-rainy-library",
                            SortOrder = 1,
                            TrackId = "track-static-sunrise"
                        },
                        new
                        {
                            Id = 6,
                            PlaylistId = "playlist-rainy-library",
                            SortOrder = 2,
                            TrackId = "track-gravity-bloom"
                        });
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Track", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AlbumId")
                        .HasColumnType("text");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "disc_number");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "duration_ms");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_local");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "track_number");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = "track-midnight-circuit",
                            AlbumId = "album-lunar-protocol",
                            DiscNumber = 1,
                            DurationMs = 213000,
                            IsLocal = false,
                            Name = "Midnight Circuit",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = "track-gravity-bloom",
                            AlbumId = "album-lunar-protocol",
                            DiscNumber = 1,
                            DurationMs = 188000,
                            IsLocal = false,
                            Name = "Gravity Bloom",
                            TrackNumber = 2
                        },
                        new
                        {
                            Id = "track-river-in-binary",
                            AlbumId = "album-feather-and-noise",
                            DiscNumber = 1,
                            DurationMs = 241000,
                            IsLocal = false,
                            Name = "River in Binary",
                            TrackNumber = 3
                        },
                        new
                        {
                            Id = "track-static-sunrise",
                            AlbumId = "album-feather-and-noise",
                            DiscNumber = 2,
                            DurationMs = 201000,
                            IsLocal = true,
                            Name = "Static Sunrise",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = "track-solar-echo",
                            AlbumId = "album-cloud-garden-ep",
                            DiscNumber = 1,
                            DurationMs = 176000,
                            IsLocal = false,
                            Name = "Solar Echo",
                            TrackNumber = 5
                        });
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.UserFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserFiles");
                });

            modelBuilder.Entity("AlbumArtist", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("spotify_swiss_knife.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("spotify_swiss_knife.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackArtist", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("spotify_swiss_knife.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Album", b =>
                {
                    b.OwnsOne("spotify_swiss_knife.Models.ExternalUrls", "ExternalUrls", b1 =>
                        {
                            b1.Property<string>("AlbumId")
                                .HasColumnType("text");

                            b1.Property<string>("Spotify")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AlbumId");

                            b1.ToTable("Albums");

                            b1.HasAnnotation("Relational:JsonPropertyName", "external_urls");

                            b1.WithOwner()
                                .HasForeignKey("AlbumId");

                            b1.HasData(
                                new
                                {
                                    AlbumId = "album-lunar-protocol",
                                    Spotify = "https://open.spotify.com/album/album-lunar-protocol"
                                },
                                new
                                {
                                    AlbumId = "album-feather-and-noise",
                                    Spotify = "https://open.spotify.com/album/album-feather-and-noise"
                                },
                                new
                                {
                                    AlbumId = "album-cloud-garden-ep",
                                    Spotify = "https://open.spotify.com/album/album-cloud-garden-ep"
                                });
                        });

                    b.OwnsMany("spotify_swiss_knife.Models.Image", "Images", b1 =>
                        {
                            b1.Property<string>("AlbumId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("Height")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "height");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "url");

                            b1.Property<int?>("Width")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "width");

                            b1.HasKey("AlbumId", "Id");

                            b1.ToTable("AlbumImages", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "images");

                            b1.WithOwner()
                                .HasForeignKey("AlbumId");

                            b1.HasData(
                                new
                                {
                                    AlbumId = "album-lunar-protocol",
                                    Id = 1,
                                    Height = 640,
                                    Url = "https://images.example.com/albums/lunar-protocol-640.jpg",
                                    Width = 640
                                },
                                new
                                {
                                    AlbumId = "album-lunar-protocol",
                                    Id = 2,
                                    Height = 300,
                                    Url = "https://images.example.com/albums/lunar-protocol-300.jpg",
                                    Width = 300
                                },
                                new
                                {
                                    AlbumId = "album-feather-and-noise",
                                    Id = 1,
                                    Height = 640,
                                    Url = "https://images.example.com/albums/feather-and-noise-640.jpg",
                                    Width = 640
                                },
                                new
                                {
                                    AlbumId = "album-feather-and-noise",
                                    Id = 2,
                                    Height = 64,
                                    Url = "https://images.example.com/albums/feather-and-noise-64.jpg",
                                    Width = 64
                                },
                                new
                                {
                                    AlbumId = "album-cloud-garden-ep",
                                    Id = 1,
                                    Height = 640,
                                    Url = "https://images.example.com/albums/cloud-garden-ep.jpg",
                                    Width = 640
                                });
                        });

                    b.Navigation("ExternalUrls")
                        .IsRequired();

                    b.Navigation("Images");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Artist", b =>
                {
                    b.OwnsOne("spotify_swiss_knife.Models.ExternalUrls", "ExternalUrls", b1 =>
                        {
                            b1.Property<string>("ArtistId")
                                .HasColumnType("text");

                            b1.Property<string>("Spotify")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ArtistId");

                            b1.ToTable("Artists");

                            b1.HasAnnotation("Relational:JsonPropertyName", "external_urls");

                            b1.WithOwner()
                                .HasForeignKey("ArtistId");

                            b1.HasData(
                                new
                                {
                                    ArtistId = "artist-luna-wave",
                                    Spotify = "https://open.spotify.com/artist/artist-luna-wave"
                                },
                                new
                                {
                                    ArtistId = "artist-neon-meadow",
                                    Spotify = "https://open.spotify.com/artist/artist-neon-meadow"
                                },
                                new
                                {
                                    ArtistId = "artist-blackbird-theory",
                                    Spotify = "https://open.spotify.com/artist/artist-blackbird-theory"
                                },
                                new
                                {
                                    ArtistId = "artist-ember-kite",
                                    Spotify = "https://open.spotify.com/artist/artist-ember-kite"
                                });
                        });

                    b.Navigation("ExternalUrls")
                        .IsRequired();
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Playlist", b =>
                {
                    b.OwnsOne("spotify_swiss_knife.Models.Owner", "Owner", b1 =>
                        {
                            b1.Property<string>("PlaylistId")
                                .HasColumnType("text");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("text")
                                .HasColumnName("Owner_DisplayName")
                                .HasAnnotation("Relational:JsonPropertyName", "display_name");

                            b1.HasKey("PlaylistId");

                            b1.ToTable("Playlists");

                            b1.HasAnnotation("Relational:JsonPropertyName", "owner");

                            b1.WithOwner()
                                .HasForeignKey("PlaylistId");

                            b1.OwnsOne("spotify_swiss_knife.Models.ExternalUrls", "ExternalUrls", b2 =>
                                {
                                    b2.Property<string>("OwnerPlaylistId")
                                        .HasColumnType("text");

                                    b2.Property<string>("Spotify")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Owner_ExternalUrls_Spotify");

                                    b2.HasKey("OwnerPlaylistId");

                                    b2.ToTable("Playlists");

                                    b2.HasAnnotation("Relational:JsonPropertyName", "external_urls");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerPlaylistId");

                                    b2.HasData(
                                        new
                                        {
                                            OwnerPlaylistId = "playlist-night-drive",
                                            Spotify = "https://open.spotify.com/user/pg"
                                        },
                                        new
                                        {
                                            OwnerPlaylistId = "playlist-rainy-library",
                                            Spotify = "https://open.spotify.com/user/pg"
                                        });
                                });

                            b1.Navigation("ExternalUrls")
                                .IsRequired();

                            b1.HasData(
                                new
                                {
                                    PlaylistId = "playlist-night-drive",
                                    DisplayName = "pg"
                                },
                                new
                                {
                                    PlaylistId = "playlist-rainy-library",
                                    DisplayName = "pg"
                                });
                        });

                    b.OwnsOne("spotify_swiss_knife.Models.ExternalUrls", "ExternalUrls", b1 =>
                        {
                            b1.Property<string>("PlaylistId")
                                .HasColumnType("text");

                            b1.Property<string>("Spotify")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PlaylistId");

                            b1.ToTable("Playlists");

                            b1.HasAnnotation("Relational:JsonPropertyName", "external_urls");

                            b1.WithOwner()
                                .HasForeignKey("PlaylistId");

                            b1.HasData(
                                new
                                {
                                    PlaylistId = "playlist-night-drive",
                                    Spotify = "https://open.spotify.com/playlist/playlist-night-drive"
                                },
                                new
                                {
                                    PlaylistId = "playlist-rainy-library",
                                    Spotify = "https://open.spotify.com/playlist/playlist-rainy-library"
                                });
                        });

                    b.OwnsMany("spotify_swiss_knife.Models.Image", "Images", b1 =>
                        {
                            b1.Property<string>("PlaylistId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("Height")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "height");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "url");

                            b1.Property<int?>("Width")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "width");

                            b1.HasKey("PlaylistId", "Id");

                            b1.ToTable("PlaylistImages", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "images");

                            b1.WithOwner()
                                .HasForeignKey("PlaylistId");

                            b1.HasData(
                                new
                                {
                                    PlaylistId = "playlist-night-drive",
                                    Id = 1,
                                    Height = 640,
                                    Url = "https://images.example.com/playlists/night-drive.jpg",
                                    Width = 640
                                },
                                new
                                {
                                    PlaylistId = "playlist-night-drive",
                                    Id = 2,
                                    Height = 300,
                                    Url = "https://images.example.com/playlists/night-drive-thumb.jpg",
                                    Width = 300
                                },
                                new
                                {
                                    PlaylistId = "playlist-rainy-library",
                                    Id = 1,
                                    Height = 640,
                                    Url = "https://images.example.com/playlists/rainy-library.jpg",
                                    Width = 640
                                });
                        });

                    b.Navigation("ExternalUrls")
                        .IsRequired();

                    b.Navigation("Images");

                    b.Navigation("Owner")
                        .IsRequired();
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.PlaylistTrackEntry", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.Playlist", "Playlist")
                        .WithMany("TrackEntries")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("spotify_swiss_knife.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Track", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.Album", "Album")
                        .WithMany("TrackList")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("spotify_swiss_knife.Models.ExternalUrls", "ExternalUrls", b1 =>
                        {
                            b1.Property<string>("TrackId")
                                .HasColumnType("text");

                            b1.Property<string>("Spotify")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TrackId");

                            b1.ToTable("Tracks");

                            b1.HasAnnotation("Relational:JsonPropertyName", "external_urls");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");

                            b1.HasData(
                                new
                                {
                                    TrackId = "track-midnight-circuit",
                                    Spotify = "https://open.spotify.com/track/track-midnight-circuit"
                                },
                                new
                                {
                                    TrackId = "track-gravity-bloom",
                                    Spotify = "https://open.spotify.com/track/track-gravity-bloom"
                                },
                                new
                                {
                                    TrackId = "track-river-in-binary",
                                    Spotify = "https://open.spotify.com/track/track-river-in-binary"
                                },
                                new
                                {
                                    TrackId = "track-static-sunrise",
                                    Spotify = "https://open.spotify.com/track/track-static-sunrise"
                                },
                                new
                                {
                                    TrackId = "track-solar-echo",
                                    Spotify = "https://open.spotify.com/track/track-solar-echo"
                                });
                        });

                    b.OwnsMany("spotify_swiss_knife.Models.Image", "Images", b1 =>
                        {
                            b1.Property<string>("TrackId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("Height")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "height");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "url");

                            b1.Property<int?>("Width")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "width");

                            b1.HasKey("TrackId", "Id");

                            b1.ToTable("TrackImages", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "images");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");

                            b1.HasData(
                                new
                                {
                                    TrackId = "track-midnight-circuit",
                                    Id = 1,
                                    Height = 640,
                                    Url = "https://images.example.com/tracks/midnight-circuit-640.jpg",
                                    Width = 640
                                },
                                new
                                {
                                    TrackId = "track-midnight-circuit",
                                    Id = 2,
                                    Height = 300,
                                    Url = "https://images.example.com/tracks/midnight-circuit-300.jpg",
                                    Width = 300
                                },
                                new
                                {
                                    TrackId = "track-gravity-bloom",
                                    Id = 1,
                                    Height = 640,
                                    Url = "https://images.example.com/tracks/gravity-bloom.jpg",
                                    Width = 640
                                },
                                new
                                {
                                    TrackId = "track-river-in-binary",
                                    Id = 1,
                                    Url = "https://images.example.com/tracks/river-in-binary.jpg"
                                },
                                new
                                {
                                    TrackId = "track-static-sunrise",
                                    Id = 1,
                                    Height = 512,
                                    Url = "https://images.example.com/tracks/static-sunrise.jpg",
                                    Width = 512
                                },
                                new
                                {
                                    TrackId = "track-solar-echo",
                                    Id = 1,
                                    Height = 640,
                                    Url = "https://images.example.com/tracks/solar-echo.jpg",
                                    Width = 640
                                },
                                new
                                {
                                    TrackId = "track-solar-echo",
                                    Id = 2,
                                    Height = 300,
                                    Url = "https://images.example.com/tracks/solar-echo-square.jpg",
                                    Width = 300
                                });
                        });

                    b.Navigation("Album");

                    b.Navigation("ExternalUrls")
                        .IsRequired();

                    b.Navigation("Images");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.UserFile", b =>
                {
                    b.HasOne("spotify_swiss_knife.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Album", b =>
                {
                    b.Navigation("TrackList");
                });

            modelBuilder.Entity("spotify_swiss_knife.Models.Playlist", b =>
                {
                    b.Navigation("TrackEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
